version: '3.8'
services:
#  gateway:
#    build: 1
#    image: gateway_image
#    container_name: gateway
#    ports:
#      - "8080:8080"
#    depends_on:
#    environment:
#      - SHAREIT_SERVER_URL=http://server:9090
#
#  server:
#    build: 1
#    image: server_image
#    container_name: server
#    ports:
#      - "9090:9090"
#    depends_on:
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:14-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_DB=shareit